LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE:=true
LOCAL_MODULE_CLASS:=STATIC_LIBRARIES
LOCAL_MODULE_TAGS:=optional
OVERRIDE_BUILT_MODULE_PATH:=
LOCAL_UNINSTALLABLE_MODULE:=true
LOCAL_SRC_FILES:=host/libmetadata_api_host.a
LOCAL_BUILT_MODULE_STEM:=libmetadata_api_host.a
LOCAL_STRIP_MODULE:=
LOCAL_MODULE:=libmetadata_api_host
LOCAL_MODULE_STEM:=libmetadata_api_host.a
LOCAL_CERTIFICATE:=
LOCAL_MODULE_PATH:=
LOCAL_REQUIRED_MODULES:=
LOCAL_SHARED_LIBRARIES:=
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE:=
LOCAL_MODULE_CLASS:=STATIC_LIBRARIES
LOCAL_MODULE_TAGS:=optional
OVERRIDE_BUILT_MODULE_PATH:=
LOCAL_UNINSTALLABLE_MODULE:=true
LOCAL_SRC_FILES:=target/libmetadata_api.a
LOCAL_BUILT_MODULE_STEM:=libmetadata_api.a
LOCAL_STRIP_MODULE:=
LOCAL_MODULE:=libmetadata_api
LOCAL_MODULE_STEM:=libmetadata_api.a
LOCAL_CERTIFICATE:=
LOCAL_MODULE_PATH:=
LOCAL_REQUIRED_MODULES:=
LOCAL_SHARED_LIBRARIES:=libstlport libc libstdc++ libm
include $(BUILD_PREBUILT)
