LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE:=true
LOCAL_MODULE_CLASS:=STATIC_LIBRARIES
LOCAL_MODULE_TAGS:=optional
LOCAL_MODULE:=libsvml
LOCAL_SRC_FILES:=host/$(LOCAL_MODULE).a
LOCAL_BUILT_MODULE_STEM:=$(LOCAL_MODULE).a
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS:=STATIC_LIBRARIES
LOCAL_MODULE_TAGS:=optional
LOCAL_MODULE:=libippacmerged
LOCAL_SRC_FILES:=target/$(LOCAL_MODULE).a
LOCAL_BUILT_MODULE_STEM:=$(LOCAL_MODULE).a
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS:=STATIC_LIBRARIES
LOCAL_MODULE_TAGS:=optional
LOCAL_MODULE:=libippccmerged
LOCAL_SRC_FILES:=target/$(LOCAL_MODULE).a
LOCAL_BUILT_MODULE_STEM:=$(LOCAL_MODULE).a
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS:=STATIC_LIBRARIES
LOCAL_MODULE_TAGS:=optional
LOCAL_MODULE:=libippdcmerged
LOCAL_SRC_FILES:=target/$(LOCAL_MODULE).a
LOCAL_BUILT_MODULE_STEM:=$(LOCAL_MODULE).a
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS:=STATIC_LIBRARIES
LOCAL_MODULE_TAGS:=optional
LOCAL_MODULE:=libippsmerged
LOCAL_SRC_FILES:=target/$(LOCAL_MODULE).a
LOCAL_BUILT_MODULE_STEM:=$(LOCAL_MODULE).a
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS:=STATIC_LIBRARIES
LOCAL_MODULE_TAGS:=optional
LOCAL_MODULE:=libippcc
LOCAL_SRC_FILES:=target/$(LOCAL_MODULE).a
LOCAL_BUILT_MODULE_STEM:=$(LOCAL_MODULE).a
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS:=STATIC_LIBRARIES
LOCAL_MODULE_TAGS:=optional
LOCAL_MODULE:=libippcv
LOCAL_SRC_FILES:=target/$(LOCAL_MODULE).a
LOCAL_BUILT_MODULE_STEM:=$(LOCAL_MODULE).a
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS:=STATIC_LIBRARIES
LOCAL_MODULE_TAGS:=optional
LOCAL_MODULE:=libippj
LOCAL_SRC_FILES:=target/$(LOCAL_MODULE).a
LOCAL_BUILT_MODULE_STEM:=$(LOCAL_MODULE).a
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LIBIPPIDIR := $(PRODUCT_OUT)/obj/STATIC_LIBRARIES/libippi_intermediates
LOCAL_MODULE_CLASS:=STATIC_LIBRARIES
LOCAL_MODULE_TAGS:=optional
LOCAL_MODULE:=libippi
LOCAL_BUILT_MODULE_STEM:=$(LOCAL_MODULE).a
GEN := $(LIBIPPIDIR)/libippi
$(GEN): $(shell mkdir -p $(LIBIPPIDIR))
$(GEN): $(shell tar xvzf $(LOCAL_PATH)/target/libippi.a.tar.gz -C $(LIBIPPIDIR))
LOCAL_SRC_FILES := ../../../../../compiled-source/obj/STATIC_LIBRARIES/libippi_intermediates/libippi.a
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS:=STATIC_LIBRARIES
LOCAL_MODULE_TAGS:=optional
LOCAL_MODULE:=libippm
LOCAL_SRC_FILES:=target/$(LOCAL_MODULE).a
LOCAL_BUILT_MODULE_STEM:=$(LOCAL_MODULE).a
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS:=STATIC_LIBRARIES
LOCAL_MODULE_TAGS:=optional
LOCAL_MODULE:=libippvm
LOCAL_SRC_FILES:=target/$(LOCAL_MODULE).a
LOCAL_BUILT_MODULE_STEM:=$(LOCAL_MODULE).a
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS:=STATIC_LIBRARIES
LOCAL_MODULE_TAGS:=optional
LOCAL_MODULE:=libipps
LOCAL_SRC_FILES:=target/$(LOCAL_MODULE).a
LOCAL_BUILT_MODULE_STEM:=$(LOCAL_MODULE).a
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS:=STATIC_LIBRARIES
LOCAL_MODULE_TAGS:=optional
LOCAL_MODULE:=libippcore
LOCAL_SRC_FILES:=target/$(LOCAL_MODULE).a
LOCAL_BUILT_MODULE_STEM:=$(LOCAL_MODULE).a
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS:=STATIC_LIBRARIES
LOCAL_MODULE_TAGS:=optional
LOCAL_MODULE:=libippscemerged
LOCAL_SRC_FILES:=target/$(LOCAL_MODULE).a
LOCAL_BUILT_MODULE_STEM:=$(LOCAL_MODULE).a
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS:=STATIC_LIBRARIES
LOCAL_MODULE_TAGS:=optional
LOCAL_MODULE:=libippscmerged
LOCAL_SRC_FILES:=target/$(LOCAL_MODULE).a
LOCAL_BUILT_MODULE_STEM:=$(LOCAL_MODULE).a
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS:=STATIC_LIBRARIES
LOCAL_MODULE_TAGS:=optional
LOCAL_MODULE:=libippsremerged
LOCAL_SRC_FILES:=target/$(LOCAL_MODULE).a
LOCAL_BUILT_MODULE_STEM:=$(LOCAL_MODULE).a
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS:=STATIC_LIBRARIES
LOCAL_MODULE_TAGS:=optional
LOCAL_MODULE:=libippsrmerged
LOCAL_SRC_FILES:=target/$(LOCAL_MODULE).a
LOCAL_BUILT_MODULE_STEM:=$(LOCAL_MODULE).a
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS:=STATIC_LIBRARIES
LOCAL_MODULE_TAGS:=optional
LOCAL_MODULE:=libippsemerged
LOCAL_SRC_FILES:=target/$(LOCAL_MODULE).a
LOCAL_BUILT_MODULE_STEM:=$(LOCAL_MODULE).a
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS:=STATIC_LIBRARIES
LOCAL_MODULE_TAGS:=optional
LOCAL_MODULE:=libiomp5
LOCAL_SRC_FILES:=target/$(LOCAL_MODULE).a
LOCAL_BUILT_MODULE_STEM:=$(LOCAL_MODULE).a
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_COPY_HEADERS:=include/ippac.h include/ippcc.h include/ippch.h include/ippcore.h include/ippcv.h include/ippdc.h include/ippdefs.h include/ippdi.h include/ipp.h include/ippi.h include/ippj.h include/ippm.h include/ippr.h include/ipp_s8.h include/ippsc.h include/ipps.h include/ippsr.h include/ippvc.h include/ippversion.h include/ippvm.h
LOCAL_COPY_HEADERS_TO:=ipp
include $(BUILD_COPY_HEADERS)
