LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE:=
LOCAL_MODULE_CLASS:=SHARED_LIBRARIES
LOCAL_MODULE_TAGS:=optional
OVERRIDE_BUILT_MODULE_PATH:=$(PRODUCT_OUT)/obj/lib
LOCAL_UNINSTALLABLE_MODULE:=
LOCAL_SRC_FILES:=target/libaudioresample.so
LOCAL_BUILT_MODULE_STEM:=libaudioresample.so
LOCAL_STRIP_MODULE:=
LOCAL_MODULE:=libaudioresample
LOCAL_MODULE_STEM:=libaudioresample.so
LOCAL_CERTIFICATE:=
LOCAL_MODULE_PATH:=$(PRODUCT_OUT)/system/lib
LOCAL_REQUIRED_MODULES:=
LOCAL_SHARED_LIBRARIES:=libc
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_COPY_HEADERS:=include/iasrc_resampler.h
LOCAL_COPY_HEADERS_TO:=libaudioresample
include $(BUILD_COPY_HEADERS)
